// Scott Kuhl

// syslog is a logging mechanism common on Unix machines. Depending on
// your machine, you can view the log in different ways. Typically the
// output will be stored in /var/log/syslog 

#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>

#include <syslog.h>

int main(void)
{
	printf("Depending on how your machine is configured, this program might cause an 'emergency' message to be broadcast to users on all terminals. You might not want to run this on a machine where other logged in users might be alarmed by the message. Press Ctrl+C to exit, any other key to continue.\n");
	char buf[100];
	if(fgets(buf, 100, stdin) == NULL)
	{
		printf("fgets error\n");
		exit(EXIT_FAILURE);
	}

	/* Prepare a disclaimer to include in our messages. */
	char disclaimer[1024];
	snprintf(disclaimer, 1024, "Everything is fine, this is a test generated by user '%s'.\n", getenv("USER"));

	/* Open a connection to the syslog */
	openlog("syslog-demonstration", LOG_CONS | LOG_PID | LOG_NDELAY, LOG_LOCAL1);

	/* Send different types of messages to the log */
	syslog(LOG_EMERG, "This is a test of the syslog emergency system. This type of message is typically used to indicate that the system is unstable. %s", disclaimer);
	syslog(LOG_ALERT, "This is an alert, action must be taken immediately. %s", disclaimer);
	syslog(LOG_CRIT, "This is a critical condition. %s", disclaimer);
	syslog(LOG_ERR, "This is a error condition. %s", disclaimer);
	syslog(LOG_WARNING, "This is a warning condition. Everything is fine, this is a test. %s", disclaimer);
	syslog(LOG_NOTICE, "This is a normal, but significant, condition. Everything is fine, this is a test. %s", disclaimer);
	syslog(LOG_NOTICE, "This is an informational message. Everything is fine, this is a test. %s", disclaimer);
	syslog(LOG_NOTICE, "This is a debugging message. Everything is fine, this is a test. %s", disclaimer);

	/* Close the log */
	closelog();

}
	
